### ISSUE TITLE
Uncaught TypeError: Cannot read property 'person' of undefined     at (index):93

### ISSUE THREAD

**Issue by Shaun2016** [neo4j-examples/movies-java-spring-data-neo4j#28]
Visit localhost:8080/movies?title=*Matrix*, we want to send get request to movie.roles._links.person.href, but movie.roles have no parameter named _links.

**Comment by viperan** [comment]
I had the same issue,  the problem is on the java script call on index.html line 93:      $.get(cast._links.person.href, function(personData) {
I change it into : $.get(cast.person.href, function(personData) { but I am still unable to get the person info. I got the Roles, but not the info. Seems like there is problem on the JQuery part of it.

**Comment by viperan** [comment]
Ok found the problem!
if you want to display the cast and the name, remove  line number  93 to 97 and replace those line with :
` var job = cast.job || "acted"; +
$list.append($("<li>" + cast.person.name + " " +job + (job == "acted"?" as " + cast.roles.join(", ") : "") + "</li>"));`

**Comment by Shaun2016** [comment]
Wow, I see that, thanks for your help.

**Comment by michael-simons** [comment]
Judging from the date of this issue, I fixed it shortly afterwards without seeing the issue.
https://github.com/neo4j-examples/movies-java-spring-data-neo4j/commit/94dacb8b391ee6d3f73874527ef84c1003e93d90
